.TH signalp 1 \" -*- nroff -*-

.SH NAME
signalp \- predict signal peptides in proteins

.SH SYNOPSIS
\fBsignalp\fP
[\fB\-fasta\fP \fIfile\fP]
[\fB-format short\fP|\fBlong\fP]
[\fB-plot png\fP|\fBeps\fP|\fBnone\fP]
[\fB-mature\fP] [\fB-batch\fP \fIinteger\fP]
[\fB-prefix\fP \fIstring\fP] [\fB-tmpdir\fP \fIpath\fP]
[\fB-org euk\fP|\fBgram+\fP|\fBgram-\fP|\fBarch\fP]
[\fB-gff3\fP] [\fB-version\fP]
.SH DESCRIPTION
.B signalp 
predicts the presence of signal peptides and the location of their cleavage sites in proteins from Archaea, Gram-positive Bacteria, Gram-negative Bacteria and Eukarya. In Bacteria and Archaea, SignalP 5.0 can discriminate between three types of signal peptides Sec/SPI (standard signal peptide), Sec/SPII (lipoprotein signal peptide) and Tat/SPI (tat signal peptide). SignalP 5.0 is based on a deep convolutional and recurrent neural network architecture including a conditional random field.

The method is described in detail in the references quoted below.

.B Input

The input is taken from \fIfile\fP or, if no file is specified, the standard
input. The input format, described below, is Pearson \fBFASTA\fP.

Each sequence must be preceded by a sequence header line starting with the
symbol `>' immediately followed by a unique name (identifier) of the
sequence. The input sequences are expected to have unique names;
if a sequence name is repeated only the last sequence with that name will
be processed. The rest of the header line, separated from the sequence name
by whitespace, is ignored. 

The sequences must be written using the one letter abbreviations
for the amino acids:

     \fBacdefghiklmnpqrstvwy\fP or \fBACDEFGHIKLMNPQRSTVWY\fP

Other letters and digits will be converted to `X' and treated as
unknown amino acids. Other characters like blanks will be ignored.

Only the first 70 N-terminal amino acids are used for predictions.	

.B Output

The user can obtain the results of the run in various formats:

A prediction summary (tabular file containing 1. the protein prediction (SP(Sec/SPI) / LIPO(Sec/SPII) / TAT(Tat/SPI) / OTHER) and the associated likelihood probability and 2. the cleavage site position and associated likelihood probability. NOTE: if the cleavage site position is "?", it means that the cleavage site is out range due to a probable protein fragment as input.)

Processed entries fasta (a FASTA sequence file containing the sequences of protein that had predicted signal peptides, with the signal peptide removed)

Processed entries gff3 (a file showing the signal peptides feature of those proteins that had predicted signal peptides in GFF3 format).

A plot, three likelihood probabilities are reported on the plot, i.e. SP(Sec/SPI) / LIPO(Sec/SPII) / TAT(Tat/SPI) (depending on what type of signal peptide is predicted), CS (the cleavage site) and OTHER (the probability that the sequence does not have any kind of signal peptide).

A tabular file with the numeric likelihood probabilities used in the plot.

.SH OPTIONS
.TP
.BI \-fasta  " file"
Input file in fasta format.
.TP
.BI \-batch " integer"
Number of sequences that the tool will run simultaneously. Decrease or increase size depending on your system memory. (default 10000). Note: this option will have an effect also on the computation speed. A larger batch size will mean faster computation at the expense of using more memory. The default batch size of 10000 will use approximately 1.5 GB of memory.
.TP
.BI \-format  " string"
Output format. 'long' for generating the predictions with plots, 'short' for the predictions without plots. (default "short")
.RS
.TP
.B short
Summary prediction without plots.
.TP
.B long
Summary prediction with plots.
.RE
.TP
.BI \-gff3 " "

Make gff3 file of processed sequences.
.TP
.BI \-mature " "
Make fasta file with mature sequence.
.TP
.BI \-org " string"
Specify organism that the network will use. The valid types are:

        \fBeuk\fP       eukaryotes (\fBdefault\fP)
.br
        \fBgram-\fP     Gram-negative bacteria
.br
        \fBgram+\fP     Gram-positive bacteria
.br
        \fBarch\fP      Archaea
.TP
.BI \-plot " string"
Plots output format. When long output selected, choose between 'png', 'eps' or 'none' to get just a tabular file. (default "png").
.TP
.BI \-prefix " string" 
Output files prefix. (default "Input file prefix")
.TP
.BI \-tmpdir " string" 
Specify temporary file directory. (default "System default tmpdir")
.TP
.BI \-stdout " "
Write the prediction summary to the STDOUT.
.TP
.BI \-verbose " "
Verbose output. Specify '-verbose=false' to avoid printing. (default true)
.TP
.BI \-version
Prints version.
.TP

.SH VERSION
This manual page describes SignalP 5.0b, from June 2019. Additional information
can be found at:

.B	http://www.cbs.dtu.dk/services/SignalP/

.SH PROBLEMS AND QUESTIONS
In the case of technical problems (bugs etc.) please contact
.B jjalma@dtu.dk.

Questions on the scientific aspects of the SignalP method should go to
Henrik Nielsen, henni@dtu.dk.

.SH REFERENCES

.B Ver. 5.0

"SignalP 5.0 improves signal peptide predictions using deep neural networks"
Jose Juan Almagro Armenteros, Konstantinos D. Tsirigos, Casper Kaae Sonderby, Thomas Nordahl Petersen, Ole Winther, Soren Brunak, Gunnar von Heijne and Henrik Nielsen.
Nature Biotechnology, doi:10.1038/s41587-019-0036-z (2019)

.B Ver. 4.0

"SignalP 4.0 - Discrimination between Signal Peptides and Transmembrane
Regions"
.br
Thomas Nordahl Petersen, Søren Brunak, Gunnar von Heijne and Henrik Nielsen.
.br
Nature Methods, 8:785-786, 2011.

.B Ver. 3.0

"Improved prediction of signal peptides - SignalP 3.0"
Jannick Dyrloev Bendtsen, Henrik Nielsen, Gunnar von Heijne
(*) and Soren Brunak.
Journal of Molecular Biology: accepted 2004.

.B Ver. 2.0

"Prediction of signal peptides and signal anchors by a
hidden Markov model",
Henrik Nielsen and Anders Krogh
In: Proceedings of the Sixth International Conference on
Intelligent Systems for Molecular Biology (ISMB 6), AAAI
Press, Menlo Park, California, pages 122-130, 1998.

.B Ver. 1.1
(original paper)

"Identification of prokaryotic and eukaryotic signal
peptides and prediction of their cleavage sites",
Henrik Nielsen, Jacob Engelbrecht, Soren Brunak and Gunnar
von Heijne (*)
Protein Engineering, vol. 10, pages 1-6, 1997.


Center for Biological Sequence Analysis
The Technical University of Denmark
DK-2800 Lyngby, Denmark

(*) Department of Biochemistry
Arrhenius Laboratory
Stockholm University
S-106 91 Stockholm, Sweden

.SH SEE ALSO
chlorop(1), targetp(1), fasta(1)
